apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: features.edward.tech
spec:
  group: edward.tech
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: features
    singular: feature
    kind: Feature
    shortNames:
      - f
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            name:
              type: string
            active:
              type: boolean
            attributes:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  restriction:
                    type: string
                  values:
                    type: array
                    items:
                      type: string
