apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: features
rules:
  - apiGroups: ["edward.tech"]
    resources: ["features"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: features
subjects:
  - kind: ServiceAccount
    name: default # "name" is case sensitive
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: features # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: "rbac.authorization.k8s.io"
---