apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: features-demo-app
spec:
  rules:
    - host: $(Values.config.spec.domain)
      http:
        paths:
          - path: /
            backend:
              serviceName: random-data-generator
              servicePort: 80
