name: PR Automation
on:
  pull_request:
jobs:
  merge_pr_if_required:
    name: Merge PR if required
    runs-on: ubuntu-latest
    steps:
      - name: PR Automation
        uses: devjoes/pr-automation@v0.1.0
        with:
          token: ${{ secrets.CUSTOM_TOKEN }}
          autoCloseLabel: automated-pr
          warnClosingAfter: 1h
          autoCloseAfterWarn: 30m
          deleteOnClose: true
          deleteOnMerge: true
          branchBlackList: totally-random-branch
