name: Build & Release Documentation
on:
  push:
    branches:
      - master
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_BUILD_REF: ${{ github.run_id }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Packages and Build
        run: |
          cd ./documentation-site/
          npm i
          npm run build
      - name: Clear Existing Docs
        run: cd ./docs/; rm -rfv *; echo "features.edward.tech" >> ./CNAME; cd ../documentation-site
      - name: Move new docs to Folder
        run: mv ./documentation-site/build/* ./docs
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2.8.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Updated documentation to new version as part of build ${{github.run_id}}
          branch: update-documentation-${{github.run_id}}
          base: master
