name: Publish Nuget Package
on:
  release:
    types:
      - created
env:
  NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Dotnet Runtime
        run: sudo apt-get install -y dotnet-runtime-3.1
      - name: Pack and Push Nuget Package
        run: |
          cd ./packages/nuget/Features
          dotnet restore "Features/Features.csproj"
          dotnet restore "Features.Tests/Features.Tests.csproj"
          dotnet test "Features.Tests/Features.Tests.csproj" -c Release
          export PACKAGE_VERSION=${GITHUB_REF##*/}
          PACKAGE_VERSION=${PACKAGE_VERSION#?}
          dotnet pack /p:Version=${PACKAGE_VERSION} -o .
          dotnet nuget push Features.${PACKAGE_VERSION}.nupkg -k ${NUGET_TOKEN} -s https://api.nuget.org/v3/index.json